# Generated by Django 4.0 on 2021-12-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Owner', verbose_name='image __  صوره المالكين')),
                ('OwTitle', models.CharField(max_length=40, verbose_name='Name __ اسم ')),
                ('OwTitle_ar', models.CharField(max_length=40, verbose_name='Name __  اسم عربي ')),
                ('OwExperience', models.CharField(max_length=30, verbose_name='Experience __ الخبره ')),
                ('OwExperience_ar', models.CharField(max_length=30, verbose_name='Experience __  الخبره بال عربي ')),
                ('OwDesc', models.CharField(max_length=150, verbose_name='Description __ وصف')),
                ('OwDesc_ar', models.CharField(max_length=150, verbose_name='Description __ وصف بال عربي')),
            ],
            options={
                'verbose_name': 'Owner __ مالكين الشركه ',
                'verbose_name_plural': 'Owner __ مالكين الشركه ',
            },
        ),
    ]
