# Generated by Django 4.0 on 2021-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='ImgBacHome',
            field=models.ImageField(default='', upload_to='Owner/ImgBacHome', verbose_name='image __  صوره الخلفيه الرائسيه'),
            preserve_default=False,
        ),
    ]
