# Generated by Django 3.2.5 on 2021-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrTitle_en', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('PrTitle_ar', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('PrPricing_en', models.CharField(max_length=30, verbose_name='Pricing en __ السعار بالدولار')),
                ('PrPricing_ar', models.CharField(max_length=30, verbose_name='Pricing ar __ الاسعار بالجنيه')),
                ('PrDescription_en', models.TextField(max_length=200, verbose_name='Description en __ وصف الاسعار ')),
                ('PrDescription_ar', models.TextField(max_length=200, verbose_name='Description ar __ وصف الاسعار ')),
            ],
            options={
                'verbose_name': 'Pricing __ الاسعار با متر',
                'verbose_name_plural': 'Pricing __ الاسعار با متر',
            },
        ),
        migrations.CreateModel(
            name='Pricing_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrTitle_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title_T en __ وسم الواجهه الرئسي')),
                ('PrTitle_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title_T ar __ وسم الواجهه الرئسي')),
                ('PrDescription_en', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description en __ وصف الواجهه الرئسي')),
                ('PrDescription_ar', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description ar __ وصف الواجهه الرئسي')),
            ],
            options={
                'verbose_name': ' Pricing  __  وصف الاسعار',
                'verbose_name_plural': ' Pricing  __  وصف الاسعار',
            },
        ),
    ]
