# Generated by Django 3.2.5 on 2021-12-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency symbol __  اسم العملات')),
            ],
        ),
        migrations.AddField(
            model_name='pricing_card',
            name='Currency_symbol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pricing.currency_symbol', verbose_name='Currency symbol __ اختار العمله'),
            preserve_default=False,
        ),
    ]
