# Generated by Django 3.2.5 on 2021-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0002_auto_20211221_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSpaces', models.CharField(blank=True, max_length=10, null=True, verbose_name='Spaces __ المساحات')),
            ],
        ),
    ]
