# Generated by Django 3.2.5 on 2021-12-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0003_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_card',
            name='PRSpaces',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pricing.spaces', verbose_name='spaces __  اختار المساحات '),
            preserve_default=False,
        ),
    ]
