# Generated by Django 3.2.5 on 2021-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0004_pricing_card_prspaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_card',
            name='PrPricing_ar',
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PrTitle_ar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title AR'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PrTitle_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title EN'),
        ),
    ]
