# Generated by Django 3.2.5 on 2021-12-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0005_auto_20211221_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing_card',
            old_name='PrPricing_en',
            new_name='PrPricing',
        ),
    ]
