# Generated by Django 3.2.5 on 2021-12-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0006_rename_prpricing_en_pricing_card_prpricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency_symbol',
            options={'verbose_name_plural': 'Currency symbol'},
        ),
        migrations.AlterModelOptions(
            name='pricing_card',
            options={'verbose_name': 'Pricing_Card', 'verbose_name_plural': 'Pricing_Card'},
        ),
        migrations.AlterModelOptions(
            name='pricing_t',
            options={'verbose_name': 'Pricing_T', 'verbose_name_plural': ' Pricing_T'},
        ),
        migrations.AlterModelOptions(
            name='spaces',
            options={'verbose_name_plural': 'spaces'},
        ),
        migrations.AlterField(
            model_name='currency_symbol',
            name='Currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency symbol'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='Currency_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.currency_symbol', verbose_name='Currency symbol'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PRSpaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.spaces', verbose_name='spaces'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PrDescription_ar',
            field=models.TextField(max_length=200, verbose_name='Description AR'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PrDescription_en',
            field=models.TextField(max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='pricing_card',
            name='PrPricing',
            field=models.CharField(max_length=30, verbose_name='Pricing'),
        ),
        migrations.AlterField(
            model_name='pricing_t',
            name='PrDescription_ar',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description ar'),
        ),
        migrations.AlterField(
            model_name='pricing_t',
            name='PrDescription_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description en'),
        ),
        migrations.AlterField(
            model_name='pricing_t',
            name='PrTitle_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title_T ar '),
        ),
        migrations.AlterField(
            model_name='pricing_t',
            name='PrTitle_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title_T en'),
        ),
        migrations.AlterField(
            model_name='spaces',
            name='SSpaces',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Spaces'),
        ),
    ]
