# Generated by Django 3.2.5 on 2021-12-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0007_auto_20211221_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing_card',
            options={'verbose_name': 'Pricing Card Detail', 'verbose_name_plural': 'Pricing Card Detail'},
        ),
        migrations.AlterModelOptions(
            name='pricing_t',
            options={'verbose_name': 'Pricing_Text_Home', 'verbose_name_plural': ' Pricing_Text_Home'},
        ),
    ]
