# Generated by Django 3.2.5 on 2021-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0008_auto_20211221_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_card',
            name='PrPricing',
            field=models.NullBooleanField(max_length=30, verbose_name='Pricing'),
        ),
    ]
