# Generated by Django 3.2.5 on 2021-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0009_alter_pricing_card_prpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_card',
            name='PrPricing',
            field=models.CharField(default='', max_length=30, verbose_name='Pricing'),
            preserve_default=False,
        ),
    ]
