# Generated by Django 3.2.5 on 2021-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0010_alter_pricing_card_prpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_card',
            name='PrPricing',
            field=models.CharField(max_length=7, verbose_name='Pricing'),
        ),
    ]
