# Generated by Django 4.0 on 2021-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TImg', models.ImageField(upload_to='Team', verbose_name='image')),
                ('TeTitle', models.CharField(max_length=15, verbose_name='Title')),
                ('TeTitle_ar', models.CharField(max_length=15, verbose_name='Title arabic')),
                ('TeExperience', models.CharField(max_length=20, verbose_name='Experience')),
                ('TeExperience_ar', models.CharField(max_length=20, verbose_name='Experience arabic')),
            ],
            options={
                'verbose_name': 'Team __ المهندسون',
                'verbose_name_plural': 'Team __ المهندسون',
            },
        ),
    ]
