# Generated by Django 4.0 on 2021-12-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='team.team')),
                ('Fac', models.URLField(blank=True, verbose_name='Facebook')),
                ('Insta', models.URLField(blank=True, verbose_name='instagram')),
                ('Lin', models.URLField(blank=True, verbose_name='linkedin')),
                ('beh', models.URLField(blank=True, verbose_name='behance')),
            ],
            bases=('team.team',),
        ),
    ]
