# Generated by Django 4.0 on 2021-12-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASTitle_en', models.CharField(blank=True, max_length=100, verbose_name='Title en __ وسم انجلزي ')),
                ('ASTitle_ar', models.CharField(blank=True, max_length=100, verbose_name='Title ar __ وسم عربي')),
                ('UsDescription_en', models.TextField(blank=True, max_length=200, verbose_name='Description en __ وصف انجلزي')),
                ('UsDescription_ar', models.TextField(blank=True, max_length=200, verbose_name='Description ar __ وصف عربي')),
                ('ASTitle_1_en', models.CharField(blank=True, max_length=50, verbose_name='Title en 1 __ وسم انجلزي ')),
                ('ASTitle_1_ar', models.CharField(blank=True, max_length=50, verbose_name='Title ar 1 __ وسم عربي')),
                ('ASDescription_1_en', models.TextField(blank=True, max_length=100, verbose_name='Description en 1 __ وصف انجلزي')),
                ('ASDescription_1_ar', models.TextField(blank=True, max_length=100, verbose_name='Description ar 1 __ وصف عربي')),
                ('ASTitle_2_en', models.CharField(blank=True, max_length=50, verbose_name='Title en 2 __ وسم انجلزي ')),
                ('ASTitle_2_ar', models.CharField(blank=True, max_length=50, verbose_name='Title ar 2 __ وسم عربي')),
                ('ASDescription_2_en', models.TextField(blank=True, max_length=100, verbose_name='Description en 2 __ وصف انجلزي')),
                ('ASDescription_2_ar', models.TextField(blank=True, max_length=100, verbose_name='Description ar 2 __ وصف عربي')),
                ('ASTitle_3_en', models.CharField(blank=True, max_length=50, verbose_name='Title en 3 __ وسم انجلزي ')),
                ('ASTitle_3_ar', models.CharField(blank=True, max_length=50, verbose_name='Title ar 3 __ وسم عربي')),
                ('ASDescription_3_en', models.TextField(blank=True, max_length=100, verbose_name='Description en 3 __ وصف انجلزي')),
                ('ASDescription_3_ar', models.TextField(blank=True, max_length=100, verbose_name='Description ar 3 __ وصف عربي')),
            ],
            options={
                'verbose_name': 'About_Section  __  قصم المعلومات الاساسي',
                'verbose_name_plural': 'About_Section  __  قصم المعلومات الاساسي',
            },
        ),
    ]
