# Generated by Django 4.0 on 2022-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_1_ar',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_1_en',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description  1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_2_ar',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_2_en',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_3_ar',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description  3 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_3_en',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description  3 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_1_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title 1 __ وسم '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_1_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title 1 __ وسم  '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_2_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title  2 __ وسم '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_2_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title  2 __ وسم  '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_3_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title  3 __ وسم '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_3_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title  3 __ وسم  '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title __ وسم '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASTitle_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title __ وسم '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='UsDescription_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='UsDescription_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description __ وصف '),
        ),
    ]
