# Generated by Django 4.2.6 on 2023-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_all', '0002_alter_about_section_asdescription_1_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_1_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_1_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description  1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_2_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_2_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_3_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description  3 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='ASDescription_3_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description  3 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='UsDescription_ar',
            field=models.TextField(blank=True, max_length=0, verbose_name='Description __ وصف '),
        ),
        migrations.AlterField(
            model_name='about_section',
            name='UsDescription_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description __ وصف '),
        ),
    ]
