# Generated by Django 4.2.6 on 2023-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_all', '0003_alter_about_section_asdescription_1_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_section',
            name='UsDescription_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description __ وصف '),
        ),
    ]
