# Generated by Django 3.2.9 on 2021-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_info_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='place',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='site',
            field=models.CharField(max_length=20),
        ),
    ]
