# Generated by Django 3.2.9 on 2021-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211128_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='emails',
            field=models.EmailField(max_length=20),
        ),
    ]
