# Generated by Django 3.2.9 on 2021-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_info_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='info',
            name='emails',
            field=models.EmailField(max_length=25),
        ),
    ]
