# Generated by Django 4.0 on 2021-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20211128_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='info',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='info',
            name='phones_number',
        ),
        migrations.AddField(
            model_name='info',
            name='PuData',
            field=models.CharField(blank=True, max_length=20, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='info',
            name='email_2',
            field=models.EmailField(blank=True, max_length=30, verbose_name='email __ 2'),
        ),
        migrations.AddField(
            model_name='info',
            name='phone1_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone_number 1'),
        ),
        migrations.AddField(
            model_name='info',
            name='phone2_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phones_number 2'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=25, verbose_name='email 1'),
        ),
        migrations.AlterField(
            model_name='info',
            name='place',
            field=models.CharField(blank=True, max_length=20, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='info',
            name='site',
            field=models.CharField(blank=True, max_length=20, verbose_name='site'),
        ),
    ]
