# Generated by Django 4.0 on 2021-12-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_info_options_remove_info_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='PuData',
            field=models.CharField(blank=True, max_length=100, verbose_name=' الموعيد العمل __ DATA '),
        ),
    ]
