# Generated by Django 3.2.5 on 2021-12-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_info_pudata'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='PuData_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name=' الموعيد العمل بال عربي __ DATA '),
        ),
    ]
