# Generated by Django 4.0 on 2022-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_info_pudata_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email_2',
            field=models.EmailField(blank=True, max_length=30, verbose_name='email 2'),
        ),
        migrations.AlterField(
            model_name='info',
            name='place',
            field=models.CharField(blank=True, max_length=30, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='info',
            name='site',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
    ]
