# Generated by Django 4.0 on 2022-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_info_email_2_alter_info_place_alter_info_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='place_ar',
            field=models.CharField(blank=True, max_length=30, verbose_name='country ar'),
        ),
        migrations.AddField(
            model_name='info',
            name='site_ar',
            field=models.CharField(blank=True, max_length=20, verbose_name='City ar'),
        ),
    ]
