# Generated by Django 4.0 on 2021-12-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='External_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interior_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LandScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiTitle', models.CharField(blank=True, max_length=100, verbose_name='Title name')),
                ('TiDesc', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Services_T __  اسم و الوصف',
            },
        ),
        migrations.CreateModel(
            name='ShowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SDImg_1', models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 1')),
                ('SDImg_2', models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 1')),
                ('SDTitle_1', models.CharField(blank=True, max_length=25, verbose_name='Title Project -- ')),
                ('SDDescriptions', models.CharField(blank=True, max_length=25, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('SDImg_3', models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 1')),
                ('SDTitle_2', models.CharField(blank=True, max_length=25, verbose_name='Title Project -- ')),
                ('SDDescriptions_2', models.CharField(blank=True, max_length=25, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('SDImg_4', models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 1')),
                ('SDTitle_3', models.CharField(blank=True, max_length=25, verbose_name='Title Project -- ')),
                ('SDDescriptions_3', models.CharField(blank=True, max_length=25, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'Urban Design __   تفصيل الخدمه',
            },
        ),
        migrations.CreateModel(
            name='Urban_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(blank=True, max_length=25, verbose_name='Name Services __ اسم الخدمه')),
                ('UDescriptions', models.CharField(blank=True, max_length=25, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'Urban Design __  التصميم الحضري',
            },
        ),
    ]
