# Generated by Django 4.0 on 2021-12-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='External_Design',
        ),
        migrations.DeleteModel(
            name='Interior_Design',
        ),
        migrations.DeleteModel(
            name='LandScape',
        ),
        migrations.DeleteModel(
            name='ShowDetail',
        ),
        migrations.DeleteModel(
            name='Urban_Design',
        ),
    ]
