# Generated by Django 4.0 on 2021-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_delete_external_design_delete_interior_design_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urban_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(blank=True, max_length=25, verbose_name='Name Services __ اسم الخدمه')),
                ('UDescriptions', models.CharField(blank=True, max_length=25, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'Urban Design __  التصميم الحضري',
            },
        ),
    ]
