# Generated by Django 4.0 on 2021-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_external_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
