# Generated by Django 4.0 on 2021-12-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_interior_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions',
            field=models.TextField(blank=True, max_length=700, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_2',
            field=models.TextField(blank=True, max_length=700, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_3',
            field=models.TextField(blank=True, max_length=700, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
    ]
