# Generated by Django 4.0 on 2021-12-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_showdetail_sddescriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_2',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_3',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
    ]
