# Generated by Django 4.0 on 2021-12-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_alter_showdetail_sddescriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urban_design',
            name='UDescriptions',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
    ]
