# Generated by Django 4.0 on 2021-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_alter_urban_design_udescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showdetail',
            old_name='SDDescriptions_3',
            new_name='SDDescriptions_1',
        ),
        migrations.RemoveField(
            model_name='showdetail',
            name='SDTitle_3',
        ),
    ]
