# Generated by Django 4.0 on 2021-12-12 19:45

import Services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_rename_sddescriptions_3_showdetail_sddescriptions_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdetail',
            name='image',
            field=models.ImageField(default='', upload_to=Services.models.image_upload),
            preserve_default=False,
        ),
    ]
