# Generated by Django 4.0 on 2021-12-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_showdetail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landscape',
            options={'verbose_name_plural': 'Land Scape  __  المناظر الطبيعيه'},
        ),
        migrations.AddField(
            model_name='landscape',
            name='LSDescription',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='LSName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
