# Generated by Django 4.0 on 2021-12-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_alter_landscape_options_landscape_lsdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscape',
            name='LSDescription',
            field=models.TextField(max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
    ]
