# Generated by Django 4.0 on 2021-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_alter_landscape_lsdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandScapeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LSImg_1', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('LSDescriptions', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('LSImg_2', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('LSTitle_1', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('LSDescriptions_1', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('LSImg_4', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('LSImg_3', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('LSTitle_2', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('LSDescriptions_2', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'Land Scape  __  تفصيل المناظر الطبيعيه',
            },
        ),
    ]
