# Generated by Django 4.0 on 2021-12-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_landscapedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDesignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDDImg_1', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('EDDDescriptions', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('EDDImg_2', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('EDDTitle_1', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('EDDDescriptions_1', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('EDDImg_4', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('EDDImg_3', models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 1')),
                ('EDDTitle_2', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('EDDDescriptions_2', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'External Design  __  تفصيل التصميم الخارجي',
            },
        ),
        migrations.AlterModelOptions(
            name='external_design',
            options={'verbose_name_plural': 'External Design  __  السفحه الرئسيه لل التصميم الخارجي'},
        ),
        migrations.AddField(
            model_name='external_design',
            name='EDDescription',
            field=models.TextField(default='', max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='external_design',
            name='EDName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
