# Generated by Django 4.0 on 2021-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_externaldesigndetail_alter_external_design_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interior_design',
            options={'verbose_name_plural': 'Interior Design  __  السفحه الرئسيه لل تصميم داخلي'},
        ),
        migrations.AddField(
            model_name='interior_design',
            name='IDDescription',
            field=models.TextField(default='', max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interior_design',
            name='IDName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
