# Generated by Django 4.0 on 2021-12-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_alter_interior_design_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior_DesignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDDImg_1', models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 1')),
                ('IDDDescriptions', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('IDDImg_2', models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 1')),
                ('IDDTitle_1', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('IDDDescriptions_1', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
                ('IDDImg_4', models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 1')),
                ('IDDImg_3', models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 1')),
                ('IDDTitle_2', models.CharField(blank=True, max_length=200, verbose_name='Title Project -- ')),
                ('IDDDescriptions_2', models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه')),
            ],
            options={
                'verbose_name_plural': 'Interior Design  __  تفاصيل تصميم داخلي',
            },
        ),
        migrations.AlterModelOptions(
            name='externaldesigndetail',
            options={'verbose_name_plural': 'External Design  __  تفاصيل التصميم الخارجي'},
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 1'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 1'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 1'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 1'),
        ),
    ]
