# Generated by Django 4.0 on 2021-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_interior_designdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='external_design',
            options={'verbose_name_plural': 'External Design  __  الصفحه الرئسيه لل التصميم الخارجي'},
        ),
        migrations.AlterModelOptions(
            name='landscape',
            options={'verbose_name_plural': 'Land Scape  __ الصفحه الرئسيه لل المناظر الطبيعيه'},
        ),
        migrations.AlterModelOptions(
            name='landscapedetail',
            options={'verbose_name_plural': 'Land Scape  __  تفاصيل المناظر الطبيعيه'},
        ),
        migrations.AlterModelOptions(
            name='services_t',
            options={'verbose_name_plural': 'Services_T __ الصفحه الرئسيه اسم و الوصف'},
        ),
        migrations.AlterModelOptions(
            name='showdetail',
            options={'verbose_name_plural': 'Urban Design __ تفاصيل التصميم الحضري  '},
        ),
        migrations.AlterModelOptions(
            name='urban_design',
            options={'verbose_name_plural': 'Urban Design __ الصفحه الرئسيه لل التصميم الحضري '},
        ),
    ]
