# Generated by Django 3.2.5 on 2021-12-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_alter_external_design_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_t',
            name='TiDesc_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description -- العنوان عربي'),
        ),
        migrations.AddField(
            model_name='services_t',
            name='TiTitle_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title name -- الاسم عربي'),
        ),
    ]
