# Generated by Django 3.2.5 on 2021-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_auto_20211214_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_design',
            name='EDImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/External_Design', verbose_name='Images 1'),
        ),
        migrations.AddField(
            model_name='interior_design',
            name='IDImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/Interior_Design', verbose_name='Images 1'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='LSImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/LandScape', verbose_name='Images 1'),
        ),
        migrations.AddField(
            model_name='urban_design',
            name='UDImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/Urban Design', verbose_name='Images 1'),
        ),
    ]
