# Generated by Django 3.2.5 on 2021-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0021_auto_20211214_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='urban_design',
            name='UDescriptions_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='urban_design',
            name='UName_ar',
            field=models.CharField(blank=True, max_length=25, verbose_name='Name Services __ اسم الخدمه'),
        ),
    ]
