# Generated by Django 3.2.5 on 2021-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0022_auto_20211214_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdetail',
            name='SDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='showdetail',
            name='SDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='showdetail',
            name='SDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __   وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='showdetail',
            name='SDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AddField(
            model_name='showdetail',
            name='SDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- وصف الخدمه بال عربي'),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UDescriptions_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descriptions Services __ وصف الخدماه بالعربي'),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UName_ar',
            field=models.CharField(blank=True, max_length=25, verbose_name='Name Services __ اسم الخدمه بالعربي'),
        ),
    ]
