# Generated by Django 3.2.5 on 2021-12-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0023_auto_20211214_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='LSDescriptio_ar',
            field=models.TextField(default='', max_length=300, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landscape',
            name='LSName_ar',
            field=models.CharField(default='', max_length=30, verbose_name='العنوان عربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landscapedetail',
            name='LSDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='landscapedetail',
            name='LSDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='landscapedetail',
            name='LSDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AddField(
            model_name='landscapedetail',
            name='LSTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AddField(
            model_name='landscapedetail',
            name='LSTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='LSName',
            field=models.CharField(max_length=30, verbose_name='Name '),
        ),
    ]
