# Generated by Django 3.2.5 on 2021-12-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_auto_20211214_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landscape',
            old_name='LSDescriptio_ar',
            new_name='LSDescription_ar',
        ),
    ]
