# Generated by Django 3.2.5 on 2021-12-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0025_rename_lsdescriptio_ar_landscape_lsdescription_ar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaldesigndetail',
            old_name='EDDDescriptions_2',
            new_name='EDDDescriptions_1_ar',
        ),
        migrations.AddField(
            model_name='external_design',
            name='EDDescription_ar',
            field=models.TextField(default='', max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='external_design',
            name='EDName_ar',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='externaldesigndetail',
            name='EDDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AddField(
            model_name='externaldesigndetail',
            name='EDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
    ]
