# Generated by Django 3.2.5 on 2021-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0026_auto_20211214_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_design',
            name='EDDescription_ar',
            field=models.TextField(max_length=300, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 2'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 4'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 3'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- اسم الخدمه بال عربي '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project --  اسم '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- اسم الخدمه بال عربي'),
        ),
    ]
