# Generated by Django 3.2.5 on 2021-12-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0027_auto_20211214_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior_design',
            name='IDDescription_ar',
            field=models.TextField(default='', max_length=300, verbose_name='Descriptions Services __ وصف الخدمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interior_design',
            name='IDName_ar',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interior_designdetail',
            name='IDDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='interior_designdetail',
            name='IDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='interior_designdetail',
            name='IDDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه'),
        ),
        migrations.AddField(
            model_name='interior_designdetail',
            name='IDDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
        migrations.AddField(
            model_name='interior_designdetail',
            name='IDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- '),
        ),
    ]
