# Generated by Django 3.2.5 on 2021-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0028_auto_20211214_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services __ وصف الخدمه بال عربي'),
        ),
    ]
