# Generated by Django 3.2.5 on 2021-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0029_alter_interior_designdetail_idddescriptions_2_ar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services_t',
            options={'verbose_name_plural': 'Services_Text Home __ الصفحه الرئسيه اسم و الوصف'},
        ),
        migrations.AlterModelOptions(
            name='showdetail',
            options={'verbose_name_plural': 'Urban Design Detail __ تفاصيل  '},
        ),
        migrations.RemoveField(
            model_name='showdetail',
            name='image',
        ),
        migrations.AlterField(
            model_name='services_t',
            name='TiDesc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='services_t',
            name='TiDesc_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description AR'),
        ),
        migrations.AlterField(
            model_name='services_t',
            name='TiTitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title name EN '),
        ),
        migrations.AlterField(
            model_name='services_t',
            name='TiTitle_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title name  AR'),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UDImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/Urban Design', verbose_name=' Images '),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UDescriptions',
            field=models.CharField(blank=True, max_length=300, verbose_name=' Descriptions Services '),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UDescriptions_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name=' وصف الخدمه  '),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UName',
            field=models.CharField(blank=True, max_length=25, verbose_name=' Name Services '),
        ),
        migrations.AlterField(
            model_name='urban_design',
            name='UName_ar',
            field=models.CharField(blank=True, max_length=25, verbose_name=' اسم الخدمه '),
        ),
    ]
