# Generated by Django 3.2.5 on 2021-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0030_auto_20211221_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscape',
            name='LSDescription',
            field=models.TextField(max_length=300, verbose_name='Descriptions EN '),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='LSDescription_ar',
            field=models.TextField(max_length=300, verbose_name='Descriptions AR '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  EN __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_1',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions AR __ وصف الخدمه '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_2',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions AR __ وصف الخدمه '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  AR __وصف الخدمه '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDImg_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 2'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 3'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/ShowDetail', verbose_name='Images 4'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN -- 1'),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR -- '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project 2 '),
        ),
        migrations.AlterField(
            model_name='showdetail',
            name='SDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project 2'),
        ),
    ]
