# Generated by Django 3.2.5 on 2021-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0031_auto_20211221_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='external_design',
            options={'verbose_name_plural': 'External Design  __ الصفحه الرئسيه  '},
        ),
        migrations.AlterField(
            model_name='external_design',
            name='EDDescription',
            field=models.TextField(max_length=300, verbose_name='Descriptions EN'),
        ),
        migrations.AlterField(
            model_name='external_design',
            name='EDDescription_ar',
            field=models.TextField(max_length=300, verbose_name='Descriptions AR'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  AR '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 3'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/ExternalDesignDetail', verbose_name='Images 4'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descriptions  EN '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN __ وصف الخدمه'),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions_1',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions AR '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions_2',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  AR'),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions AR  __ وصف الخدمه '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 3'),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/LandScapeDetail', verbose_name='Images 4'),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSTitle_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN '),
        ),
        migrations.AlterField(
            model_name='landscapedetail',
            name='LSTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR '),
        ),
    ]
