# Generated by Django 3.2.5 on 2021-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0032_auto_20211221_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_2_en',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  EN '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR '),
        ),
    ]
