# Generated by Django 3.2.5 on 2021-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0033_auto_20211221_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaldesigndetail',
            options={'verbose_name_plural': ' External Design  __  تفاصيل '},
        ),
        migrations.AlterModelOptions(
            name='interior_design',
            options={'verbose_name_plural': 'Interior Design  __  السفحه الرئسيه '},
        ),
        migrations.AlterModelOptions(
            name='interior_designdetail',
            options={'verbose_name_plural': 'Interior Design  __  تفاصيل '},
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  EN'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_1',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions EN'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions  AR '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions AR '),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project -- EN'),
        ),
        migrations.AlterField(
            model_name='externaldesigndetail',
            name='EDDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR'),
        ),
        migrations.AlterField(
            model_name='interior_design',
            name='IDDescription',
            field=models.TextField(max_length=300, verbose_name='Descriptions EN'),
        ),
        migrations.AlterField(
            model_name='interior_design',
            name='IDDescription_ar',
            field=models.TextField(max_length=300, verbose_name='Descriptions AR'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services EN'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_1',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services EN'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_1_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services AR'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_2',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services EN '),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_2_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services AR '),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDDescriptions_ar',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriptions Services AR'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDImg_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 2'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDImg_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 3'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDImg_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/Interior_DesignDetail', verbose_name='Images 4'),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDTitle_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN '),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDTitle_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR '),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDTitle_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project EN '),
        ),
        migrations.AlterField(
            model_name='interior_designdetail',
            name='IDDTitle_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title Project AR '),
        ),
    ]
