# Generated by Django 4.0 on 2021-12-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='clients', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Client  __  العملاء المتعامل معه الشركه',
                'verbose_name_plural': 'Client  __  العملاء المتعامل معه الشركه',
            },
        ),
    ]
