# Generated by Django 3.2.5 on 2021-12-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
