# Generated by Django 3.2.5 on 2021-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Title',
            new_name='CLTitle',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
        migrations.AddField(
            model_name='clients',
            name='CLimage',
            field=models.ImageField(blank=True, upload_to='clients', verbose_name='image'),
        ),
    ]
