# Generated by Django 4.0 on 2021-12-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About')),
                ('AOTitle_1_en', models.CharField(blank=True, max_length=100, verbose_name='Title 1 en __ وسم ')),
                ('AOTitle_1_ar', models.CharField(blank=True, max_length=100, verbose_name='Title 1 ar __ وسم ')),
                ('AODescription_1_en', models.TextField(blank=True, max_length=200, verbose_name='Description 1 en __ وصف ')),
                ('AODescription_1_ar', models.TextField(blank=True, max_length=200, verbose_name='Description 1 ar __ وصف ')),
                ('AOTitle_2_en', models.CharField(blank=True, max_length=100, verbose_name='Title 2 en __ وسم ')),
                ('AOTitle_2_ar', models.CharField(blank=True, max_length=100, verbose_name='Title 2 ar __ وسم ')),
                ('AODescription_2_en', models.TextField(blank=True, max_length=200, verbose_name='Description 2 en __ وصف ')),
                ('AODescription_2_ar', models.TextField(blank=True, max_length=200, verbose_name='Description 2 ar __ وصف ')),
                ('AOTitle_3_en', models.CharField(blank=True, max_length=100, verbose_name='Title 3 en __ وسم ')),
                ('AOTitle_3_ar', models.CharField(blank=True, max_length=100, verbose_name='Title 3 ar __ وسم ')),
                ('AODescription_3_en', models.TextField(blank=True, max_length=200, verbose_name='Description 3 en __ وصف ')),
                ('AODescription_3_ar', models.TextField(blank=True, max_length=200, verbose_name='Description 3 ar __ وصف ')),
                ('AOTitle_4_en', models.CharField(blank=True, max_length=100, verbose_name='Title 4 en __ وسم ')),
                ('AOTitle_4_ar', models.CharField(blank=True, max_length=100, verbose_name='Title 4 ar __ وسم ')),
                ('AODescription_4_en', models.TextField(blank=True, max_length=200, verbose_name='Description 4 en __ وصف ')),
                ('AODescription_4_ar', models.TextField(blank=True, max_length=200, verbose_name='Description 4 ar __ وصف ')),
            ],
            options={
                'verbose_name': 'About  __  حول الشركه',
                'verbose_name_plural': 'About  __  حول الشركه',
            },
        ),
    ]
