# Generated by Django 4.0 on 2022-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='AODescription_1_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_1_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_2_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 2  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_2_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_3_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 3  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_3_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 3  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_4_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 4  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_4_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description 4  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_1_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 1 __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_1_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 1 __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_2_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 2  __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_2_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 2  __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_3_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 3  __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_3_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 3  __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_4_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 4  __ وسم '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AOTitle_4_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title 4  __ وسم '),
        ),
    ]
