# Generated by Django 4.2.6 on 2023-11-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_aodescription_1_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='imageRestaurants')),
            ],
            options={
                'verbose_name': 'image Restaurants',
                'verbose_name_plural': 'image Restaurants',
            },
        ),
    ]
