# Generated by Django 4.2.6 on 2023-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_imagerestaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerestaurants',
            name='titleImg',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
