# Generated by Django 4.2.6 on 2023-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_imagerestaurants_titleimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='AODescription_1_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_1_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 1 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_2_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 2  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_2_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 2 __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_3_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 3  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_3_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 3  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_4_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 4  __ وصف '),
        ),
        migrations.AlterField(
            model_name='about',
            name='AODescription_4_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description 4  __ وصف '),
        ),
    ]
