# Generated by Django 3.2.5 on 2021-12-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_ars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titles', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title __  وسم')),
            ],
            options={
                'verbose_name_plural': 'Category  __  قصم',
            },
        ),
        migrations.CreateModel(
            name='Category_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title __  وسم')),
            ],
            options={
                'verbose_name_plural': 'Category  __  قصم',
            },
        ),
    ]
