# Generated by Django 3.2.5 on 2021-12-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSTitle', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title Project __ اسم المشروع')),
                ('PSTitle_ar', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title Project __ اسم المشروع عربي')),
                ('PSData', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('PSDescription', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('PSDescription_ar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='وصف المشرواع')),
                ('PSImg', models.ImageField(upload_to='media/Portfolio', verbose_name='images Projects Home | carousel |  __  صورة المشروع الاساسي')),
                ('PSImgUp_0', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 0 carousel')),
                ('PSImgUp_00', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 00 carousel')),
                ('PSImgUp_1', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 1 Height 19∶25')),
                ('PSImgUp_2', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 2 Height 19∶25')),
                ('PSImgUp_3', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 3 Height 19∶25')),
                ('PSImgUp_4', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 4 Width | Rendered aspect ratio:\t1169∶750')),
                ('PSImgUp_5', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 5 Height 19∶25')),
                ('PSImgUp_6', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 6 Width | Height 19∶25')),
                ('PSImgUp_7', models.ImageField(blank=True, upload_to='media/Portfolio', verbose_name='images 7 Width | Rendered aspect ratio:\t1169∶750')),
                ('LSlug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio __ قسم المشاريع',
            },
        ),
    ]
