# Generated by Django 3.2.5 on 2021-12-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_portfoliolists'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliolists',
            name='PSCategorys',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.category_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliolists',
            name='PSCategorys_ar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.category_ars'),
            preserve_default=False,
        ),
    ]
