# Generated by Django 4.0 on 2021-12-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20211217_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolists',
            name='PSCategorys',
        ),
        migrations.RemoveField(
            model_name='portfoliolists',
            name='PSCategorys_ar',
        ),
    ]
