# Generated by Django 4.0 on 2021-12-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_remove_portfoliolists_pscategorys_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_ars',
            options={'verbose_name_plural': 'Category ar __  قصم عربي'},
        ),
    ]
