# Generated by Django 4.0 on 2021-12-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_alter_category_ars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_ars',
            options={'verbose_name_plural': 'Category __  قصم'},
        ),
    ]
