# Generated by Django 4.0 on 2021-12-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_alter_category_ars_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliolists',
            name='PLCategoryf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.category_ars'),
            preserve_default=False,
        ),
    ]
