# Generated by Django 4.0 on 2021-12-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_portfoliolists_plcategoryf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 1 Height 19∶25'),
        ),
    ]
