# Generated by Django 4.0 on 2021-12-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_alter_portfoliolists_psimgup_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 2 Height 19∶25'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 3 Height 19∶25'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 4 Width | Rendered aspect ratio:\t1169∶750'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 5 Height 19∶25'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 6 Width | Height 19∶25'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSImgUp_7',
            field=models.ImageField(blank=True, null=True, upload_to='media/Portfolio', verbose_name='images 7 Width | Rendered aspect ratio:\t1169∶750'),
        ),
    ]
