# Generated by Django 3.2.5 on 2021-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_alter_portfoliolists_psimgup_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSTitle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title Project EN  اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='portfoliolists',
            name='PSTitle_ar',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title Project AR __ اسم المشروع '),
        ),
    ]
