# Generated by Django 4.0 on 2022-01-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0010_auto_20211221_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_ars',
            options={'verbose_name_plural': 'Category __   قسم'},
        ),
        migrations.AlterModelOptions(
            name='portfoliolists',
            options={'verbose_name_plural': 'Portfolio Add __  اضافة المشاريع'},
        ),
    ]
