# Generated by Django 4.0 on 2021-12-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About')),
                ('UsTitle', models.CharField(blank=True, max_length=100, verbose_name='Title 1')),
                ('UsTitlet', models.TextField(blank=True, max_length=200, verbose_name='Description 1')),
                ('UsTitles', models.CharField(blank=True, max_length=100, verbose_name='Title 2')),
                ('UsTitlese', models.TextField(blank=True, max_length=200, verbose_name='Description 2')),
                ('UsTitlm', models.CharField(blank=True, max_length=100, verbose_name='Title 3')),
                ('UsTitlems', models.TextField(blank=True, max_length=200, verbose_name='Description 3')),
                ('UsTitleo', models.CharField(blank=True, max_length=100, verbose_name='Title 4')),
                ('UsTitleyo', models.TextField(blank=True, max_length=200, verbose_name='Description 4')),
            ],
            options={
                'verbose_name': 'About  __  حول الشركه',
                'verbose_name_plural': 'About  __  حول الشركه',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='clients', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Client  __  العملاء المتعامل معه الشركه',
                'verbose_name_plural': 'Client  __  العملاء المتعامل معه الشركه',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaqName', models.CharField(blank=True, max_length=30, verbose_name='Title Name Header')),
                ('FaqTitle', models.CharField(blank=True, max_length=100, verbose_name='Description Header')),
                ('FaqNameOne', models.CharField(blank=True, max_length=100, verbose_name='FAQ Name __  الاساله ')),
                ('FaqDescription', models.TextField(blank=True, max_length=200, verbose_name='FAQ Description __ الاجابه')),
            ],
            options={
                'verbose_name': 'FAQ  __  الاساله والاجوبه',
                'verbose_name_plural': 'FAQ  __  الاساله والاجوبه',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTitle', models.CharField(blank=True, max_length=20, verbose_name='Title home page')),
                ('HoDescription', models.TextField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Welcome To Homepage  __  الواجه الاماميه',
                'verbose_name_plural': 'Welcome To Homepage  __  الواجه الاماميه',
            },
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fac', models.URLField(blank=True, verbose_name='Facebook')),
                ('Insta', models.URLField(blank=True, verbose_name='instagram')),
                ('Twi', models.URLField(blank=True, verbose_name='twitter')),
                ('Lin', models.URLField(blank=True, verbose_name='linkedin')),
                ('Sci', models.URLField(blank=True, verbose_name='Skype')),
                ('beh', models.URLField(blank=True, verbose_name='behance')),
                ('tel', models.URLField(blank=True, verbose_name='telegram')),
                ('wha', models.URLField(blank=True, verbose_name='whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='NavHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NaLogo', models.CharField(blank=True, max_length=15, verbose_name='Name Site __  اسم الموقع')),
            ],
            options={
                'verbose_name': 'NavHeader  __  Logo الموقع',
                'verbose_name_plural': 'NavHeader  __  Logo الموقع',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Owner', verbose_name='Title')),
                ('OwTitle', models.CharField(max_length=40, verbose_name='Title')),
                ('OwExperience', models.CharField(max_length=30, verbose_name='Title')),
                ('OwDesc', models.CharField(max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Owner __ مالكين الشركه ',
                'verbose_name_plural': 'Owner __ مالكين الشركه ',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Portfolio  __  المعرض',
                'verbose_name_plural': 'Portfolio  __  المعرض',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrTitle', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('PrDesc', models.TextField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': ' Pricing  __  وصف الاسعار',
                'verbose_name_plural': ' Pricing  __  وصف الاسعار',
            },
        ),
        migrations.CreateModel(
            name='Section_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsTitle', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('UsDescription', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('UsTitl1', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('UsDescription1', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('UsTitl2', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('UsDescription2', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('UsTitl3', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('UsDescription3', models.TextField(blank=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Section_old  __  قصم المعلومات الاساسي',
                'verbose_name_plural': 'Section_old  __  قصم المعلومات الاساسي',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TImg', models.ImageField(upload_to='Team', verbose_name='image')),
                ('TeTitle', models.CharField(max_length=15, verbose_name='Title')),
                ('TeExperience', models.CharField(max_length=20, verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Team __ المهندسون',
                'verbose_name_plural': 'Team __ المهندسون',
            },
        ),
        migrations.CreateModel(
            name='Pricing1',
            fields=[
                ('pricing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vira.pricing')),
                ('PrTitles', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('PrPricing', models.CharField(max_length=30, verbose_name='Pricing')),
                ('PrDescription', models.TextField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Pricing __ الاسعار با متر',
                'verbose_name_plural': 'Pricing __ الاسعار با متر',
            },
            bases=('vira.pricing',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerTitle', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('SerHid', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('SerFor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vira.portfolio', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Services  __  ماهي الخدمات الذي تقدمه الشركه',
                'verbose_name_plural': 'Services  __  ماهي الخدمات الذي تقدمه الشركه',
            },
        ),
    ]
