# Generated by Django 4.0 on 2021-12-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
    ]
