# Generated by Django 4.0 on 2021-12-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0002_alter_clients_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
    ]
