# Generated by Django 4.0 on 2021-12-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0003_remove_clients_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='OwDesc',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='OwExperience',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='OwTitle',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='image',
        ),
    ]
