# Generated by Django 4.0 on 2021-12-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0004_alter_owner_options_remove_owner_owdesc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.RemoveField(
            model_name='services',
            name='SerFor',
        ),
        migrations.RemoveField(
            model_name='services',
            name='SerHid',
        ),
        migrations.RemoveField(
            model_name='services',
            name='SerTitle',
        ),
    ]
