# Generated by Django 4.0 on 2021-12-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0005_alter_services_options_remove_services_serfor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='TImg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeExperience',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeTitle',
        ),
    ]
