# Generated by Django 4.0 on 2021-12-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0006_alter_team_options_remove_team_timg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navheader',
            name='NaLogo_ar',
            field=models.CharField(blank=True, max_length=15, verbose_name='Name Site __   اسم الموقع عربي'),
        ),
    ]
