# Generated by Django 4.0 on 2021-12-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0007_navheader_nalogo_ar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='HoDescription',
            new_name='HoDescription_ar',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='HoTitle',
            new_name='HoTitle_ar',
        ),
        migrations.AddField(
            model_name='homepage',
            name='HoDescription_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='HoTitle_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title home page'),
        ),
    ]
