# Generated by Django 4.0 on 2021-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0008_rename_hodescription_homepage_hodescription_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section_old',
            options={},
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsDescription',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsDescription1',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsDescription2',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsDescription3',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsTitl1',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsTitl2',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsTitl3',
        ),
        migrations.RemoveField(
            model_name='section_old',
            name='UsTitle',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HoDescription_ar',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description __  وصف عربي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HoDescription_en',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description en __  وصف انجلزي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HoTitle_ar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title home page ar __ وسم عربي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HoTitle_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Title home page en __ وسم انجلزي '),
        ),
    ]
