# Generated by Django 4.0 on 2021-12-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0009_alter_section_old_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
    ]
