# Generated by Django 4.0 on 2021-12-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0010_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitlems',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitleo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitles',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitlese',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitlet',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitleyo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='UsTitlm',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
