# Generated by Django 3.2.5 on 2021-12-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0011_alter_about_options_remove_about_ustitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricing1',
            options={},
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='PrDesc',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='PrTitle',
        ),
        migrations.RemoveField(
            model_name='pricing1',
            name='PrDescription',
        ),
        migrations.RemoveField(
            model_name='pricing1',
            name='PrPricing',
        ),
        migrations.RemoveField(
            model_name='pricing1',
            name='PrTitles',
        ),
    ]
