# Generated by Django 4.0.1 on 2022-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0012_auto_20211221_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='navheader',
            name='NavImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/header', verbose_name='Logo site'),
        ),
    ]
