# Generated by Django 4.2.6 on 2023-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0013_navheader_navimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navheader',
            name='NavImg',
            field=models.ImageField(blank=True, upload_to='media/header', verbose_name='Logo site'),
        ),
    ]
