# Generated by Django 4.2.6 on 2023-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0014_alter_navheader_navimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='HoTitle_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title home page ar __ وسم عربي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HoTitle_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title home page en __ وسم انجلزي '),
        ),
    ]
