# Generated by Django 4.2.6 on 2023-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0015_alter_homepage_hotitle_ar_alter_homepage_hotitle_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navheader',
            name='NavImg',
            field=models.ImageField(upload_to='media/header', verbose_name='Logo site'),
        ),
    ]
