# Generated by Django 4.2.6 on 2023-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0016_alter_navheader_navimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='Insta',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='Twi',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='wha',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='media',
            name='Fac',
        ),
        migrations.RemoveField(
            model_name='media',
            name='Lin',
        ),
        migrations.RemoveField(
            model_name='media',
            name='Sci',
        ),
        migrations.RemoveField(
            model_name='media',
            name='beh',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tel',
        ),
        migrations.AddField(
            model_name='media',
            name='snapchat',
            field=models.URLField(blank=True, verbose_name='snapchat'),
        ),
        migrations.AddField(
            model_name='media',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='tiktok'),
        ),
    ]
