# Generated by Django 4.2.6 on 2023-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0017_rename_insta_media_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='MTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
