# Generated by Django 4.2.6 on 2023-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vira', '0018_media_mtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='map',
            field=models.URLField(blank=True, verbose_name='map'),
        ),
    ]
